### ISSUE TITLE
wget - unresponsive console

### ISSUE THREAD

**Issue by dav009** [DH-Box/corpus-downloader#12]
it seems sometimes wget gets stuck when downloading a corpus item.
I think it would be better to use a library like requests to make the download.

this would allow more control on how to donwload the items, better exceptions but also it would get rid of doing `sh cd` in some places.

**Comment by JonathanReeve** [comment]
Thanks for the bug report! I'm happy to see people are starting to use this tool, despite it's raw state. I noticed that wget gets unresponsive, too. I think it has to do with the fact that the shell wget (via `sh`) doesn't return real-time messages, only messages after the operation has completed. So the download operating appears to be stuck, especially on a big download, because it won't show the progress until after it's done. Big problem. ([I posted on Stackoverflow about it recently.](http://stackoverflow.com/questions/38780563/using-the-python-sh-module-how-can-i-show-the-output-of-a-command-as-its-happe/38780923#38780923)) I recently swapped out `sh.wget` for a Python library called `wget` that handles downloads pythonically. `requests` would probably be even better. Anyway let me know what you think. I'll close this for now, but feel free to reopen if you're still experiencing issues.
